/**
 * =========================================
 * Title: Token Types – Classification Registry
 * =========================================
 */

export const TOKEN_TYPES = {
  KEYWORD_PROGRAM: 'KW_P',
  KEYWORD_DATATYPE: 'KW_T',
  KEYWORD_LOOP: 'KW_L',
  KEYWORD_CONDITIONAL: 'KW_C',
  KEYWORD_RESERVED: 'KW_R',
  KEYWORD_START: 'KW_START',
  KEYWORD_END: 'KW_END',
  NOISE_WORD: 'NW',
  IDENTIFIER: 'ID',
  NUMBER_LITERAL: 'NUM',
  DECIMAL_LITERAL: 'DEC',
  STRING_LITERAL: 'STR',
  BOOLEAN_LITERAL: 'BOOL',
  ASSIGNMENT_OP: 'OP_ASG',
  ARITHMETIC_OP: 'OP_AR',
  UNARY_OP: 'OP_UN',
  LOGICAL_OP: 'OP_LOG',
  RELATIONAL_OP: 'OP_REL',
  DELIMITER_LEFT_PAREN: 'DEL_LPAR',
  DELIMITER_RIGHT_PAREN: 'DEL_RPAR',
  DELIMITER_LEFT_BRACKET: 'DEL_LBRACK',
  DELIMITER_RIGHT_BRACKET: 'DEL_RBRACK',
  DELIMITER_LEFT_BRACE: 'DEL_LBRACE',
  DELIMITER_RIGHT_BRACE: 'DEL_RBRACE',
  DELIMITER_COLON: 'DEL_COL',
  DELIMITER_COMMA: 'DEL_COMMA',
  DELIMITER_SEMICOLON: 'DEL_SEMI',
  DELIMITER: 'DEL',
  STRING_INSERTION: 'SIS',
  COMMENT_SINGLE: 'CMT',
  COMMENT_MULTI: 'CMT',
  UNKNOWN: 'UNK',
  ERROR: 'ERR',
};

export const KEYWORDS = {
  function: TOKEN_TYPES.KEYWORD_PROGRAM,
  start: TOKEN_TYPES.KEYWORD_START,
  end: TOKEN_TYPES.KEYWORD_END,
  echo: TOKEN_TYPES.KEYWORD_PROGRAM,
  input: TOKEN_TYPES.KEYWORD_PROGRAM,
  return: TOKEN_TYPES.KEYWORD_RESERVED,
  struct: TOKEN_TYPES.KEYWORD_RESERVED,
  data: TOKEN_TYPES.KEYWORD_RESERVED,
  number: TOKEN_TYPES.KEYWORD_DATATYPE,
  decimal: TOKEN_TYPES.KEYWORD_DATATYPE,
  string: TOKEN_TYPES.KEYWORD_DATATYPE,
  boolean: TOKEN_TYPES.KEYWORD_DATATYPE,
  list: TOKEN_TYPES.KEYWORD_DATATYPE,
  for: TOKEN_TYPES.KEYWORD_LOOP,
  while: TOKEN_TYPES.KEYWORD_LOOP,
  do: TOKEN_TYPES.KEYWORD_LOOP,
  if: TOKEN_TYPES.KEYWORD_CONDITIONAL,
  else: TOKEN_TYPES.KEYWORD_CONDITIONAL,
  then: TOKEN_TYPES.KEYWORD_CONDITIONAL,
  switch: TOKEN_TYPES.KEYWORD_CONDITIONAL,
  case: TOKEN_TYPES.KEYWORD_CONDITIONAL,
  default: TOKEN_TYPES.KEYWORD_CONDITIONAL,
  null: TOKEN_TYPES.KEYWORD_RESERVED,
  true: TOKEN_TYPES.BOOLEAN_LITERAL,
  false: TOKEN_TYPES.BOOLEAN_LITERAL,
  continue: TOKEN_TYPES.KEYWORD_RESERVED,
  break: TOKEN_TYPES.KEYWORD_RESERVED,
  new: TOKEN_TYPES.KEYWORD_RESERVED,
  this: TOKEN_TYPES.KEYWORD_RESERVED,
  with: TOKEN_TYPES.NOISE_WORD,
  to: TOKEN_TYPES.NOISE_WORD,
  by: TOKEN_TYPES.NOISE_WORD,
};

const TOKEN_COLOR_CLASSES = {
  KW_P: 'bg-indigo-100 text-indigo-800',
  KW_T: 'bg-blue-100 text-blue-800',
  KW_L: 'bg-indigo-200 text-indigo-800',
  KW_C: 'bg-indigo-300 text-indigo-900',
  KW_R: 'bg-indigo-50 text-indigo-700',
  KW_START: 'bg-indigo-500 text-indigo-50',
  KW_END: 'bg-indigo-500 text-indigo-50',
  NW: 'bg-lime-50 text-lime-700',
  ID: 'bg-green-100 text-green-800',
  NUM: 'bg-amber-100 text-amber-800',
  DEC: 'bg-amber-200 text-amber-900',
  STR: 'bg-amber-300 text-amber-900',
  BOOL: 'bg-amber-50 text-amber-700',
  OP_ASG: 'bg-teal-600 text-teal-50',
  OP_AR: 'bg-teal-100 text-teal-800',
  OP_UN: 'bg-teal-200 text-teal-800',
  OP_LOG: 'bg-teal-300 text-teal-900',
  OP_REL: 'bg-teal-400 text-teal-900',
  CMT: 'bg-emerald-50 text-emerald-700',
  SIS: 'text-yellow-700 bg-yellow-50',
  DEL: 'bg-slate-100 text-slate-700',
  DEL_LPAR: 'bg-slate-100 text-slate-700',
  DEL_RPAR: 'bg-slate-100 text-slate-700',
  DEL_LBRACK: 'bg-slate-100 text-slate-700',
  DEL_RBRACK: 'bg-slate-100 text-slate-700',
  DEL_LBRACE: 'bg-slate-100 text-slate-700',
  DEL_RBRACE: 'bg-slate-100 text-slate-700',
  DEL_COL: 'bg-slate-100 text-slate-700',
  DEL_COMMA: 'bg-slate-100 text-slate-700',
  DEL_SEMI: 'bg-slate-100 text-slate-700',
  UNK: 'bg-red-100 text-red-800',
  ERR: 'bg-red-600 text-red-50',
};

export const getTokenTypeColor = (type) => TOKEN_COLOR_CLASSES[type] || 'text-gray-700 bg-gray-50';
